# Generated by Django 3.0.5 on 2021-03-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_thubnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thubnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thubnail'),
        ),
    ]
